### ISSUE TITLE
doesn't work w/ npm install

### ISSUE THREAD

**Issue by diminutivesloop** [AxelDeneu/hey#5]
When I run `hey npm install` nothing happens. Obviously it would be nice to know when a long-running npm install finishes so if anyone knows of a workaround I'd appreciate it.

**Comment by diminutivesloop** [comment]
Works now. Looks my computer was having other issues w/ npm unrelated to this package.

**Comment by AxelDeneu** [comment]
Hey @diminutivesloop, sorry for this late answer. This project is quite old and buggy. I plan to completly rewrite it in the next weeks. I'll keep you updated when it's done!
